# docker-compose.yml
version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: userdb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

  indexer:
    build:
      context: ./indexer
      dockerfile: Dockerfile
    depends_on:
      - elasticsearch
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_USER=user
      - DB_PASSWORD=userpassword
      - DB_NAME=userdb
      - ES_HOST=elasticsearch

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - elasticsearch
    environment:
      - ES_HOST=elasticsearch

volumes:
  elasticsearch_data:
  mysql_data:
